language: node_js
node_js:
  - node

sudo: required

services:
  - docker

script:
  - yarn run git-hook
  - yarn run upload-coverage-coveralls

after_success:
  - yarn run test-integration
  - bash ./scripts/ci-deployment/deploy.sh
