version: '2.1'

services:

  base-etl:
    build:
      context: .
    environment:
      SYNDICATION_API_KEY: ${SYNDICATION_API_KEY}
      ETL_SCHEDULE: ${ETL_SCHEDULE}
      AZURE_STORAGE_CONNECTION_STRING: '${AZURE_STORAGE_CONNECTION_STRING}'
      AZURE_TIMEOUT_MINUTES: ${AZURE_TIMEOUT_MINUTES}
      CONTAINER_NAME: ${CONTAINER_NAME}

  full-etl:
    volumes:
      - .:/code
    extends:
      service: base-etl
    volumes:
      - etl-node_modules:/code/node_modules

  full-etl-clear:
    volumes:
      - .:/code
    extends:
      service: base-etl
    command: yarn run start-clear
    volumes:
      - etl-node_modules:/code/node_modules

  partial-etl:
    volumes:
      - .:/code
    extends:
      service: base-etl
    command: yarn run start-small
    volumes:
      - etl-node_modules:/code/node_modules
      - gp-etl-partial-output:/code/output

  partial-etl-clear:
    volumes:
      - .:/code
    extends:
      service: base-etl
    command: yarn run start-small-clear
    volumes:
      - etl-node_modules:/code/node_modules
      - gp-etl-partial-output:/code/output

volumes:
  etl-node_modules:
  gp-etl-partial-output:
