version: '2.1'

services:

  base-etl:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/code
    environment:
      SYNDICATION_API_KEY: ${SYNDICATION_API_KEY}
      ETL_SCHEDULE: ${ETL_SCHEDULE}

  full-etl:
    extends:
      service: base-etl
    volumes:
      - etl-node_modules:/code/node_modules

  partial-etl:
    extends:
      service: base-etl
    command: yarn run start-small
    volumes:
      - etl-node_modules:/code/node_modules

  test-etl:
    extends:
      service: base-etl
    command: yarn test
    volumes:
      - etl-node_modules:/code/node_modules

  travis-tests:
    extends:
      service: base-etl
    command: yarn run travis
    volumes:
      - etl-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

  travis-tests-integration:
    extends:
      service: base-etl
    command: yarn run test-integration
    volumes:
      - etl-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}


volumes:
  etl-node_modules:
