version: '2'

services:

  etl:
    image: nhsuk/gp-data-etl:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: production
      SYNDICATION_API_KEY: ${SYNDICATION_API_KEY}
      ETL_SCHEDULE: ${ETL_SCHEDULE}
      AZURE_STORAGE_CONNECTION_STRING: '${AZURE_STORAGE_CONNECTION_STRING}'
      AZURE_TIMEOUT_MINUTES: ${AZURE_TIMEOUT_MINUTES}
      CONTAINER_NAME: ${CONTAINER_NAME}
    labels:
      io.rancher.container.pull_image: always
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: gp-data-etl
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json
