version: '2'

services:

  etl:
    image: nhsuk/gp-data-etl:${DOCKER_IMAGE_TAG}
    environment:
      SYNDICATION_API_KEY: ${SYNDICATION_API_KEY}
      ETL_SCHEDULE: ${ETL_SCHEDULE}
    labels:
      traefik.enable: stack
      traefik.domain: ${TRAEFIK_DOMAIN}
      traefik.port: 80
      map-public-http: 80
    volumes:
      - gp-etl-output:/code/output
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: gp-data-etl
        splunk-verify-connection: "false"
        tag: "{{`{{.ImageName}} {{.Name}} {{.FullID}}`}}"
        splunk-format: json

volumes:
  gp-etl-output:
