version: '2'

services:

  etl:
    image: nhsuk/gp-data-etl:${DOCKER_IMAGE_TAG}
    environment:
      SYNDICATION_API_KEY: ${SYNDICATION_API_KEY}
      ETL_SCHEDULE: ${ETL_SCHEDULE}
      AZURE_STORAGE_CONNECTION_STRING: '${AZURE_STORAGE_CONNECTION_STRING}'
      AZURE_TIMEOUT_MINUTES: ${AZURE_TIMEOUT_MINUTES}
      CONTAINER_NAME: ${CONTAINER_NAME}
    labels:
      io.rancher.container.pull_image: always
    volumes:
      - gp-etl-output:/code/output

volumes:
  gp-etl-output:
